import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const defaults=()=>{const day=new Date().getDay(),ops=[["Complete prescribed ACL rehab","Recovery"],["Evening mission debrief","Mind"],["Read 20 pages","Mind"]];if(day>=1&&day<=5)ops.splice(1,0,["Pre-market analysis","Trading"],["Review charts and document one lesson","Trading"]);if(day===1)ops.push(["Set weekly market plan and risk limits","Trading"]);if(day===3)ops.push(["Build one Clarified Chaos FX asset","Business"]);if(day===5)ops.push(["Complete weekly trading review","Trading"]);if(day===6)ops.push(["Clarified Chaos FX deep-work block","Business"]);if(day===0)ops.push(["Plan the week and reset the system","Mind"]);return ops};
const briefings=["“The mission is not intensity. It is repeatable excellence.”","“You do not need more noise. You need a clearer next move.”","“Capital and capacity are both protected by restraint.”","“Build the system. The system carries you when motivation does not.”"];
const config=window.AEGIS_CONFIG||{},cloudReady=Boolean(config.supabaseUrl&&config.supabaseAnonKey),sb=cloudReady?createClient(config.supabaseUrl,config.supabaseAnonKey):null,today=new Date().toLocaleDateString("en-CA"),$=s=>document.querySelector(s);
let session=null,operations=JSON.parse(localStorage.getItem("aegis-operations"))||defaults().map(([title,category])=>({title,category,completed:false})),trades=JSON.parse(localStorage.getItem("aegis-trades"))||[],missions=[];
const escape=v=>{const x=document.createElement("span");x.textContent=v;return x.innerHTML},saveLocal=()=>{localStorage.setItem("aegis-operations",JSON.stringify(operations));localStorage.setItem("aegis-trades",JSON.stringify(trades))};
function renderOperations(){$("#operations-list").innerHTML=operations.map((o,i)=>`<label class="operation ${o.completed?"done":""}"><input type="checkbox" ${o.completed?"checked":""} data-operation="${i}"><span><strong>${escape(o.title)}</strong><small>${escape(o.category)} · TODAY</small></span></label>`).join("");document.querySelectorAll("[data-operation]").forEach(input=>input.addEventListener("change",async e=>{const o=operations[Number(e.target.dataset.operation)];o.completed=e.target.checked;if(session){const {error}=await sb.from("operations").update({completed:o.completed}).eq("id",o.id);if(error)console.error(error)}else saveLocal();renderOperations()}));const done=operations.filter(o=>o.completed).length;$("#operation-count").innerHTML=`${done}<span>/${operations.length}</span>`;$("#operation-meter").style.width=`${operations.length?done/operations.length*100:0}%`;$("#operation-caption").textContent=done===operations.length?"Mission accomplished":`${operations.length-done} operations remaining`}
function renderTrades(){}
async function loadCloud(){const {data:opData,error}=await sb.from("operations").select("*").eq("scheduled_date",today).order("created_at");if(error)return console.error(error);if(opData.length)operations=opData;else{const {data,error:insertError}=await sb.from("operations").insert(defaults().map(([title,category])=>({title,category,scheduled_date:today}))).select();if(insertError)return console.error(insertError);operations=data}const {data:tradeData}=await sb.from("trade_debriefs").select("*").order("traded_at",{ascending:false}).limit(40);if(tradeData)trades=tradeData;renderOperations();renderTrades()}
function renderMissions(){}
function renderRecovery(log){const state=$("#recovery-state"),summary=$("#recovery-summary");if(!state||!summary)return;if(!log){state.textContent="—";summary.innerHTML='<div><span>No recovery reports logged yet.</span><b>Awaiting data</b></div>';return}state.textContent=log.rehab_completed?"DONE":"LOGGED";summary.innerHTML=`<div><span>Pain level</span><b>${log.pain}/10</b></div><div><span>Swelling</span><b>${log.swelling}/10</b></div><div><span>Prescribed rehab</span><b>${log.rehab_completed?"Complete":"Pending"}</b></div>`}
async function loadMissionData(){const {data:missionData,error:missionError}=await sb.from("missions").select("*").order("created_at",{ascending:false});if(missionError){console.error(missionError);return}if(missionData.length)missions=missionData;else{const seed=[{title:"Restore ACL capacity",category:"Recovery",priority:"Do now",progress:72},{title:"Execute trading process",category:"Trading",priority:"Do now",progress:86},{title:"Build Clarified Chaos FX foundation",category:"Business",priority:"Schedule",progress:41}];const {data,error}=await sb.from("missions").insert(seed).select();if(error)return console.error(error);missions=data}renderMissions();const {data:logs}=await sb.from("recovery_logs").select("*").order("logged_on",{ascending:false}).limit(1);renderRecovery(logs?.[0])}
function setAuth(){ $("#auth-button").textContent=session?.user?.email?.[0]?.toUpperCase()||"M";$(".status-pill").lastChild.textContent=session?" SECURE ACCESS":" LOCAL PROTOTYPE" }
async function bootAuth(){if(!cloudReady)return;({data:{session}}=await sb.auth.getSession());setAuth();if(session){await loadCloud();await loadMissionData();await loadMasteryRescue()}sb.auth.onAuthStateChange(async(_e,next)=>{session=next;setAuth();if(session){await loadCloud();await loadMissionData();await loadMasteryRescue()}})}
function activateView(view,updateAddress=true){if(!$("#"+view))return;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$("#"+view).classList.add("active");document.querySelectorAll(".nav-link").forEach(n=>n.classList.toggle("active",n.dataset.view===view));$("#view-title").textContent=view==="command"?"COMMAND CENTER":view.toUpperCase().replace("-"," ");if(updateAddress)history.replaceState(null,"","#"+view)}
/* Mastery rescue: keeps the section usable even if a deployment misses mastery.js. */
let masteryArea="mind",masteryMind="Book",masteryBody="health",masteryEntries=[],masterySessions=[];
const masteryTopics=["Book","Quote","Trading Note","Psychology","Space","Business","Stoicism"];
function masteryRescue(){const target=$("#mastery");if(!target)return;const current=masteryArea==="mind"?masteryTopics: ["Health","Gym","Sports","Performance"];const active=masteryArea==="mind"?masteryMind:masteryBody;const locked=["Sports","Performance"].includes(active);target.innerHTML=`<div class="section-intro"><p class="eyebrow blue-text">THE CRAFT OF MASTERY</p><h2>Build the mind. Restore the body.</h2><p>Capture what makes the next decision, session, and season better.</p></div><div class="mastery-tabs"><button class="mastery-tab ${masteryArea==="mind"?"active":""}" data-rescue-area="mind">Mind</button><button class="mastery-tab ${masteryArea==="body"?"active":""}" data-rescue-area="body">Body</button></div>${masteryArea==="mind"?`<div class="mastery-category-grid">${masteryTopics.map(topic=>`<button class="mastery-category ${topic===active?"active":""}" data-rescue-topic="${topic}"><small>${topic.toUpperCase()}</small><strong>${masteryEntries.filter(entry=>entry.category===topic).length}</strong><small>${topic==="Book"?"books and reading notes":"entries captured"}</small></button>`).join("")}</div>`:`<div class="mastery-subtabs">${current.map(topic=>`<button class="mastery-tab ${topic.toLowerCase()===active.toLowerCase()?"active":""} ${["Sports","Performance"].includes(topic)?"locked":""}" data-rescue-body="${topic.toLowerCase()}">${topic}${["Sports","Performance"].includes(topic)?" LOCKED":""}</button>`).join("")}</div>`}<div class="mastery-toolbar"><h3>${active}${locked?" — locked":""}</h3>${locked?"":`<button class="primary compact" data-rescue-add="${active}">+ Add entry</button>`}</div><div class="mastery-list">${locked?`<div class="mastery-lock"><h3>${active} locked</h3><p>Unlocks when Recovery is completed and you confirm archiving the Recovery section.</p></div>`:(masteryEntries.filter(entry=>entry.category===(active==="Gym"?"Health":active)).map(entry=>`<article class="mastery-entry"><div class="entry-meta"><span>${escape(entry.category)}</span>${entry.rating?`<b>${entry.rating}/5</b>`:""}</div><h3>${escape(entry.title)}</h3>${entry.summary?`<p>${escape(entry.summary)}</p>`:""}${entry.key_lessons?`<p><b>Key takeaways:</b> ${escape(entry.key_lessons)}</p>`:""}</article>`).join("")||`<div class="mastery-empty">Nothing logged here yet. Capture the first useful item.</div>`)}</div>`;}
async function loadMasteryRescue(){if(!session||!sb)return;const {data}=await sb.from("mastery_entries").select("*").order("created_at",{ascending:false});masteryEntries=data||[];masteryRescue()}
function setupMasteryEntryDialog(){const dialog=document.createElement("dialog");dialog.id="mastery-rescue-dialog";dialog.innerHTML=`<form method="dialog" class="dialog-card mastery-form" id="mastery-rescue-form"><button class="dialog-close" type="button" aria-label="Close">×</button><p class="eyebrow blue-text">MASTERY ENTRY</p><h2>Capture the useful thing.</h2><label>Entry type<select id="mastery-entry-type">${[...masteryTopics,"Health"].map(type=>`<option value="${type}">${type}</option>`).join("")}</select></label><label>Title<input id="mastery-entry-title" required placeholder="Name the book, note, quote, or idea" /></label><label class="book-only">Rating<select id="mastery-entry-rating"><option value="">Not rated</option>${[1,2,3,4,5].map(number=>`<option value="${number}">${number} / 5</option>`).join("")}</select></label><label>Summary / note<textarea id="mastery-entry-summary" placeholder="What is worth remembering?"></textarea></label><label class="book-only">Favorite quotes<textarea id="mastery-entry-quotes"></textarea></label><label class="book-only">Key takeaways<textarea id="mastery-entry-lessons"></textarea></label><label class="book-only">Action items<textarea id="mastery-entry-actions"></textarea></label><button class="primary" type="submit">Save entry</button></form>`;document.body.append(dialog);const type=$("#mastery-entry-type"),bookFields=()=>document.querySelectorAll("#mastery-rescue-dialog .book-only").forEach(field=>field.hidden=type.value!=="Book");type.addEventListener("change",bookFields);bookFields();dialog.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());dialog.querySelector("form").addEventListener("submit",async event=>{event.preventDefault();const category=type.value,title=$("#mastery-entry-title").value.trim();if(!title)return;const entry={category,title,rating:category==="Book"?Number($("#mastery-entry-rating").value)||null:null,summary:$("#mastery-entry-summary").value.trim()||null,favorite_quotes:category==="Book"?$("#mastery-entry-quotes").value.trim()||null:null,key_lessons:category==="Book"?$("#mastery-entry-lessons").value.trim()||null:null,action_items:category==="Book"?$("#mastery-entry-actions").value.trim()||null:null};if(session&&sb){const {error}=await sb.from("mastery_entries").insert(entry);if(error)return alert(error.message);await loadMasteryRescue()}else{masteryEntries.unshift(entry);masteryRescue()}event.target.reset();bookFields();dialog.close()})}
document.addEventListener("click",event=>{const areaButton=event.target.closest("[data-rescue-area]"),topicButton=event.target.closest("[data-rescue-topic]"),bodyButton=event.target.closest("[data-rescue-body]"),addButton=event.target.closest("[data-rescue-add]");if(areaButton){masteryArea=areaButton.dataset.rescueArea;masteryRescue()}if(topicButton){masteryArea="mind";masteryMind=topicButton.dataset.rescueTopic;masteryRescue()}if(bodyButton){masteryArea="body";masteryBody=bodyButton.dataset.rescueBody;masteryRescue()}if(addButton){const type=$("#mastery-entry-type");type.value=addButton.dataset.rescueAdd==="Gym"?"Health":addButton.dataset.rescueAdd;type.dispatchEvent(new Event("change"));$("#mastery-rescue-dialog").showModal()}});
setupMasteryEntryDialog();
document.querySelectorAll(".nav-link, [data-view-target]").forEach(link=>link.addEventListener("click",e=>{const view=link.dataset.view||link.dataset.viewTarget;if(!view)return;e.preventDefault();activateView(view)}));
setTimeout(()=>{if(location.hash)activateView(location.hash.slice(1),false)},0);
const operationDialog=$("#operation-dialog");operationDialog.querySelector(".dialog-close").addEventListener("click",event=>{event.preventDefault();operationDialog.close()});document.querySelectorAll('[data-action="add-operation"]').forEach(b=>b.addEventListener("click",()=>operationDialog.showModal()));$("#save-operation").addEventListener("click",async e=>{const title=$("#operation-input").value.trim();if(!title)return e.preventDefault();const category=$("#operation-category").value;if(session){const {data,error}=await sb.from("operations").insert({title,category,scheduled_date:today}).select().single();if(error)return console.error(error);operations.push(data)}else{operations.push({title,category,completed:false});saveLocal()}renderOperations();$("#operation-input").value=""});
const tradeDialog=$("#trade-dialog");document.querySelectorAll('[data-action="add-trade"]').forEach(b=>b.addEventListener("click",()=>tradeDialog.showModal()));$("#save-trade").addEventListener("click",async e=>{const pair=$("#trade-pair").value.trim(),r=$("#trade-r").value;if(!pair||!r)return e.preventDefault();const setup=$("#trade-setup").value.trim(),grade=$("#trade-grade").value;if(session){const {data,error}=await sb.from("trade_debriefs").insert({pair,r_multiple:r,setup,execution_grade:grade}).select().single();if(error)return console.error(error);trades.unshift(data)}else{trades.unshift({pair,r,setup,grade,time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});saveLocal()}renderTrades();$("#trade-pair").value="";$("#trade-r").value="";$("#trade-setup").value=""});
$("#new-briefing").addEventListener("click",()=>$("#briefing-text").textContent=briefings[Math.floor(Math.random()*briefings.length)]);$("#auth-button").addEventListener("click",async()=>{if(!cloudReady)return alert("Secure access will activate after the Supabase connection is added.");if(session)return alert("Secure access is active. Account settings and sign-out controls are coming next.");$("#auth-dialog").showModal()});$("#auth-dialog .dialog-close").addEventListener("click",()=>$("#auth-dialog").close());$("#send-link").addEventListener("click",async e=>{const email=$("#auth-email").value.trim();if(!email)return e.preventDefault();e.preventDefault();$("#auth-message").textContent="Sending secure link…";const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});$("#auth-message").textContent=error?error.message:"Secure link sent. Check your email."});
$("#system-date").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}).toUpperCase().replace(","," ·");renderOperations();renderTrades();masteryRescue();bootAuth();
