import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const defaults=[["Complete prescribed ACL rehab","Recovery"],["Pre-market analysis","Trading"],["Review charts and document one lesson","Trading"],["Read 20 pages","Mind"],["Evening mission debrief","Mind"]];
const briefings=["“The mission is not intensity. It is repeatable excellence.”","“You do not need more noise. You need a clearer next move.”","“Capital and capacity are both protected by restraint.”","“Build the system. The system carries you when motivation does not.”"];
const config=window.AEGIS_CONFIG||{},cloudReady=Boolean(config.supabaseUrl&&config.supabaseAnonKey),sb=cloudReady?createClient(config.supabaseUrl,config.supabaseAnonKey):null,today=new Date().toLocaleDateString("en-CA"),$=s=>document.querySelector(s);
let session=null,operations=JSON.parse(localStorage.getItem("aegis-operations"))||defaults.map(([title,category])=>({title,category,completed:false})),trades=JSON.parse(localStorage.getItem("aegis-trades"))||[];
const escape=v=>{const x=document.createElement("span");x.textContent=v;return x.innerHTML},saveLocal=()=>{localStorage.setItem("aegis-operations",JSON.stringify(operations));localStorage.setItem("aegis-trades",JSON.stringify(trades))};
function renderOperations(){$("#operations-list").innerHTML=operations.map((o,i)=>`<label class="operation ${o.completed?"done":""}"><input type="checkbox" ${o.completed?"checked":""} data-operation="${i}"><span><strong>${escape(o.title)}</strong><small>${escape(o.category)} · TODAY</small></span></label>`).join("");document.querySelectorAll("[data-operation]").forEach(input=>input.addEventListener("change",async e=>{const o=operations[Number(e.target.dataset.operation)];o.completed=e.target.checked;if(session){const {error}=await sb.from("operations").update({completed:o.completed}).eq("id",o.id);if(error)console.error(error)}else saveLocal();renderOperations()}));const done=operations.filter(o=>o.completed).length;$("#operation-count").innerHTML=`${done}<span>/${operations.length}</span>`;$("#operation-meter").style.width=`${operations.length?done/operations.length*100:0}%`;$("#operation-caption").textContent=done===operations.length?"Mission accomplished":`${operations.length-done} operations remaining`}
function renderTrades(){const target=$("#trade-log");if(!trades.length){target.innerHTML='<tr class="empty-row"><td colspan="6">No trade debriefs yet. Preserve data; log the next execution.</td></tr>';return}target.innerHTML=trades.map(t=>{const r=Number(t.r_multiple??t.r),positive=r>=0,time=t.traded_at?new Date(t.traded_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):t.time;return `<tr><td>${escape(time)}</td><td>${escape(t.pair)}</td><td>${escape(t.setup||"—")}</td><td class="${positive?"result-positive":"result-negative"}">${positive?"+":""}${r}R</td><td>${positive?"WIN":"LOSS"}</td><td>${escape(t.execution_grade??t.grade)}</td></tr>`}).join("")}
async function loadCloud(){const {data:opData,error}=await sb.from("operations").select("*").eq("scheduled_date",today).order("created_at");if(error)return console.error(error);if(opData.length)operations=opData;else{const {data,error:insertError}=await sb.from("operations").insert(defaults.map(([title,category])=>({title,category,scheduled_date:today}))).select();if(insertError)return console.error(insertError);operations=data}const {data:tradeData}=await sb.from("trade_debriefs").select("*").order("traded_at",{ascending:false}).limit(40);if(tradeData)trades=tradeData;renderOperations();renderTrades()}
function setAuth(){ $("#auth-button").textContent=session?.user?.email?.[0]?.toUpperCase()||"M";$(".status-pill").lastChild.textContent=session?" SECURE ACCESS":" LOCAL PROTOTYPE" }
async function bootAuth(){if(!cloudReady)return;({data:{session}}=await sb.auth.getSession());setAuth();if(session)await loadCloud();sb.auth.onAuthStateChange(async(_e,next)=>{session=next;setAuth();if(session)await loadCloud()})}
document.querySelectorAll(".nav-link, [data-view-target]").forEach(link=>link.addEventListener("click",e=>{const view=link.dataset.view||link.dataset.viewTarget;if(!view)return;e.preventDefault();document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(`#${view}`).classList.add("active");document.querySelectorAll(".nav-link").forEach(n=>n.classList.toggle("active",n.dataset.view===view));$("#view-title").textContent=view==="command"?"COMMAND CENTER":view.toUpperCase().replace("-"," ")}));
const operationDialog=$("#operation-dialog");document.querySelectorAll('[data-action="add-operation"]').forEach(b=>b.addEventListener("click",()=>operationDialog.showModal()));$("#save-operation").addEventListener("click",async e=>{const title=$("#operation-input").value.trim();if(!title)return e.preventDefault();const category=$("#operation-category").value;if(session){const {data,error}=await sb.from("operations").insert({title,category,scheduled_date:today}).select().single();if(error)return console.error(error);operations.push(data)}else{operations.push({title,category,completed:false});saveLocal()}renderOperations();$("#operation-input").value=""});
const tradeDialog=$("#trade-dialog");document.querySelectorAll('[data-action="add-trade"]').forEach(b=>b.addEventListener("click",()=>tradeDialog.showModal()));$("#save-trade").addEventListener("click",async e=>{const pair=$("#trade-pair").value.trim(),r=$("#trade-r").value;if(!pair||!r)return e.preventDefault();const setup=$("#trade-setup").value.trim(),grade=$("#trade-grade").value;if(session){const {data,error}=await sb.from("trade_debriefs").insert({pair,r_multiple:r,setup,execution_grade:grade}).select().single();if(error)return console.error(error);trades.unshift(data)}else{trades.unshift({pair,r,setup,grade,time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});saveLocal()}renderTrades();$("#trade-pair").value="";$("#trade-r").value="";$("#trade-setup").value=""});
$("#new-briefing").addEventListener("click",()=>$("#briefing-text").textContent=briefings[Math.floor(Math.random()*briefings.length)]);$("#auth-button").addEventListener("click",async()=>{if(!cloudReady)return alert("Secure access will activate after the Supabase connection is added.");if(session)return alert("Secure access is active. Account settings and sign-out controls are coming next.");$("#auth-dialog").showModal()});$("#auth-dialog .dialog-close").addEventListener("click",()=>$("#auth-dialog").close());$("#send-link").addEventListener("click",async e=>{const email=$("#auth-email").value.trim();if(!email)return e.preventDefault();e.preventDefault();$("#auth-message").textContent="Sending secure link…";const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});$("#auth-message").textContent=error?error.message:"Secure link sent. Check your email."});
$("#system-date").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}).toUpperCase().replace(","," ·");renderOperations();renderTrades();bootAuth();
